language: java

env:
  global:
    - SONATYPE_USERNAME=pietvandongen
    - secure: "XH+9DqSZ2F9LV0Tj1KgRiuXs0OiuQBt45vAGHoGFWuMmE78wpt/fzlR5aC5xfjTUpPIwehxtqS8SSFasPouTGkzde7i+kNc0leLEfvN2Z8WhMkj7zCJ18gAyx2dgq0juBI6lW89sjLm9ui1WC7zdKWBWmHOqt3GD578wlPc4AB4="

jdk:
- oraclejdk7

after_success:
- mvn clean deploy -DcontinuousIntegration=true
